version: "3.9"

services:
  linux:
    image: amd64/ubuntu
    platform: linux/amd64
    entrypoint: /bin/bash
    # stdin_open: true
    cpus: 4
    tty: true
    ports:
    - 3027:3027
    volumes:
    - ./bridge:/bridge